import { createClient } from "https://esm.sh/@supabase/supabase-js@2?target=deno";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Send new lead notification email via Resend
async function sendNewLeadEmail(
  clientEmail: string,
  clientName: string,
  companyName: string,
  leadId: string
) {
  const resendApiKey = Deno.env.get('RESEND_API_KEY');
  if (!resendApiKey) {
    console.warn('RESEND_API_KEY not configured, skipping email');
    return { success: false, error: 'Email not configured' };
  }

  const dashboardUrl = 'https://app.hireflow.co.uk/client/leads'; // Update to your domain

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${resendApiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'Hireflow <noreply@hireflow.co.uk>', // Update to your verified domain
      to: [clientEmail],
      subject: `New Lead Assigned: ${companyName}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #10b981;">New Lead in Your Account!</h1>
          <p>Hi ${clientName},</p>
          <p>Great news! A new lead has been assigned to your account:</p>

          <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h2 style="margin: 0 0 10px 0; color: #1f2937;">${companyName}</h2>
            <p style="margin: 0; color: #6b7280;">Log in to view full details and contact information.</p>
          </div>

          <a href="${dashboardUrl}" style="display: inline-block; background-color: #10b981; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin: 20px 0;">
            View Lead Details
          </a>

          <p style="color: #6b7280; font-size: 14px; margin-top: 30px;">
            This lead was generated by the Hireflow team based on your requirements.
          </p>

          <p>Best regards,<br>The Hireflow Team</p>
        </div>
      `,
    }),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    console.error('Resend API error:', errorBody);
    return { success: false, error: errorBody };
  }

  const result = await response.json();
  console.log('New lead email sent successfully:', result.id);
  return { success: true, emailId: result.id };
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) throw new Error('Missing authorization header');

    const token = authHeader.replace('Bearer ', '');
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? ''
    );

    const { data: { user }, error: authError } = await supabaseClient.auth.getUser(token);
    if (authError) {
      console.error('Auth error:', authError);
      throw new Error(`Unauthorized: ${authError.message}`);
    }
    if (!user) {
      throw new Error('Unauthorized: No user found');
    }

    const { data: isAdmin } = await supabaseClient.rpc('is_admin', { _user_id: user.id });
    if (!isAdmin) throw new Error('Admin access required');

    // Now we receive the Airtable client ID directly from the frontend
    const { leadId, airtableClientId } = await req.json();
    if (!leadId) throw new Error('Lead ID is required');
    if (!airtableClientId) throw new Error('Airtable Client ID is required');

    const airtableToken = Deno.env.get('AIRTABLE_API_TOKEN');
    const airtableBaseId = Deno.env.get('AIRTABLE_BASE_ID');
    if (!airtableToken || !airtableBaseId) throw new Error('Airtable configuration missing');

    console.log('Assigning lead:', leadId, 'to Airtable client:', airtableClientId);

    // Directly update the lead with the Airtable client ID
    const tableName = encodeURIComponent('Qualified Lead Table');
    const airtableUrl = `https://api.airtable.com/v0/${airtableBaseId}/${tableName}/${leadId}`;

    const response = await fetch(airtableUrl, {
      method: 'PATCH',
      headers: {
        'Authorization': `Bearer ${airtableToken}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        fields: { 'Clients': [airtableClientId] }
      })
    });

    if (!response.ok) {
      const errorBody = await response.text();
      console.error('Airtable API Error:', {
        status: response.status,
        statusText: response.statusText,
        body: errorBody,
        url: airtableUrl,
        airtableClientId
      });

      // Parse error for user-friendly message
      try {
        const errorJson = JSON.parse(errorBody);
        if (errorJson.error?.type === 'ROW_DOES_NOT_EXIST') {
          throw new Error('Lead or Client not found in Airtable. Please refresh the page.');
        }
        if (errorJson.error?.type === 'INVALID_REQUEST_UNKNOWN') {
          throw new Error('Invalid Airtable field. Check that the Clients field exists.');
        }
      } catch (parseError) {
        if (parseError instanceof Error && parseError.message.includes('Please')) {
          throw parseError;
        }
      }

      throw new Error(`Failed to assign lead in Airtable: ${response.status}`);
    }

    const result = await response.json();
    console.log('Successfully assigned lead:', result.id, 'to client:', airtableClientId);

    // Get lead details for the email (company name)
    const companyName = result.fields?.['Company Name'] || 'New Lead';

    // Look up the client's email from Supabase profiles
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    );

    const { data: clientProfile } = await supabaseAdmin
      .from('profiles')
      .select('id, client_name')
      .eq('airtable_client_id', airtableClientId)
      .single();

    if (clientProfile) {
      // Get the user's email from auth
      const { data: userData } = await supabaseAdmin.auth.admin.getUserById(clientProfile.id);

      if (userData?.user?.email) {
        const emailResult = await sendNewLeadEmail(
          userData.user.email,
          clientProfile.client_name || 'Client',
          companyName,
          leadId
        );
        console.log('Email notification result:', emailResult);
      } else {
        console.warn('Could not find email for client profile:', clientProfile.id);
      }
    } else {
      console.warn('No Supabase profile found for Airtable client:', airtableClientId);
    }

    return new Response(
      JSON.stringify({ success: true }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error assigning lead to client:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return new Response(
      JSON.stringify({
        error: errorMessage,
        details: error instanceof Error ? error.stack : undefined
      }),
      { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
